
import React, { useState, useEffect } from 'react';
import {
  Box,
  Card,
  CardContent,
  Typography,
  Grid,
  Button,
  Chip,
  Tabs,
  Tab,
  CircularProgress,
  Alert,
  Paper,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemSecondaryAction,
  IconButton
} from '@mui/material';
import {
  Description as DocIcon,
  Download as DownloadIcon,
  Badge as IdIcon,
  CloudUpload as UploadIcon,
  Folder as FolderIcon,
  Image as ImageIcon,
  PictureAsPdf as PdfIcon,
  DirectionsCar as CarIcon
} from '@mui/icons-material';
import { jsPDF } from 'jspdf';
import { useAuth } from '../../context/AuthContext';
import { useNotification } from '../../context/NotificationContext';
import dataService from '../../services/dataService';

const Documents = () => {
  const { user } = useAuth();
  const { showNotification } = useNotification();
  const [tabValue, setTabValue] = useState(0);
  const [documents, setDocuments] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchDocuments();
  }, [user]);

  const fetchDocuments = async () => {
    try {
      setLoading(true);
      const result = await dataService.getDocuments();
      if (result && result.documents) {
        setDocuments(result.documents);
      }
    } catch (err) {
      console.error(err);
      setError('Failed to load documents');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = (doc) => {
    showNotification(`Downloading ${doc.title}...`, 'info');
    
    try {
      const pdf = new jsPDF();
      
      // Add Header
      pdf.setFillColor(25, 118, 210); // Primary Blue
      pdf.rect(0, 0, 210, 40, 'F');
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(22);
      pdf.text("INSURANCE CORP", 20, 25);
      
      // Add Content
      pdf.setTextColor(0, 0, 0);
      pdf.setFontSize(18);
      pdf.text(doc.title, 20, 60);
      
      pdf.setFontSize(12);
      pdf.setTextColor(80, 80, 80);
      pdf.text(`Document ID: ${doc.id}`, 20, 75);
      pdf.text(`Date Generated: ${new Date().toLocaleDateString()}`, 20, 85);
      
      if (doc.policyNumber) {
        pdf.text(`Policy Number: ${doc.policyNumber}`, 20, 95);
      }

      if (doc.metadata) {
        let y = 110;
        pdf.setFontSize(14);
        pdf.setTextColor(0, 0, 0);
        pdf.text("Details:", 20, y);
        y += 10;
        pdf.setFontSize(12);
        pdf.setTextColor(60, 60, 60);
        Object.entries(doc.metadata).forEach(([key, value]) => {
          pdf.text(`${key.toUpperCase()}: ${value}`, 30, y);
          y += 10;
        });
      }
      
      pdf.setLineWidth(0.5);
      pdf.line(20, 250, 190, 250);
      pdf.setFontSize(10);
      pdf.text("This document is officially generated by Insurance Corp AI System.", 20, 260);

      pdf.save(`${doc.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
      
      setTimeout(() => {
        showNotification('Download complete', 'success');
      }, 500);

    } catch (err) {
      console.error("PDF Generation Error:", err);
      showNotification('Failed to generate PDF', 'error');
    }
  };

  const handleUploadClick = () => {
    // Trigger hidden file input
    document.getElementById('doc-upload-input').click();
  };

  const handleFileChange = (event) => {
    const file = event.target.files[0];
    if (file) {
      showNotification(`Uploading ${file.name}...`, 'info');
      // Simulate upload process
      setTimeout(() => {
        const newDoc = {
          id: `doc_upload_${Date.now()}`,
          title: file.name,
          type: 'Upload',
          date: new Date().toISOString(),
          category: 'personal'
        };
        setDocuments(prev => [...prev, newDoc]);
        showNotification('Upload successful', 'success');
      }, 1500);
    }
  };

  const idCards = documents.filter(d => d.type === 'ID Card');
  const contracts = documents.filter(d => d.type === 'Contract');
  const uploads = documents.filter(d => d.type === 'Upload');

  const IdCardView = ({ doc }) => (
    <Paper 
      elevation={3} 
      sx={{ 
        width: '100%', 
        maxWidth: 400, 
        height: 240, 
        borderRadius: 3, 
        overflow: 'hidden', 
        position: 'relative',
        background: 'linear-gradient(135deg, #1976d2 0%, #0d47a1 100%)',
        color: 'white',
        mb: 2,
        transition: 'transform 0.2s',
        '&:hover': { transform: 'scale(1.02)' }
      }}
    >
      <Box p={3} display="flex" flexDirection="column" height="100%">
        <Box display="flex" justifyContent="space-between" alignItems="center" mb={2}>
          <Typography variant="h6" fontWeight="bold" sx={{ opacity: 0.9 }}>INSURANCE CORP</Typography>
          <IdIcon sx={{ opacity: 0.8 }} />
        </Box>
        
        <Box flex={1}>
          <Typography variant="caption" sx={{ opacity: 0.7 }}>POLICY NUMBER</Typography>
          <Typography variant="h6" sx={{ letterSpacing: 1, mb: 1 }}>{doc.policyNumber}</Typography>
          
          <Grid container spacing={1}>
            <Grid item xs={6}>
              <Typography variant="caption" sx={{ opacity: 0.7 }}>INSURED</Typography>
              <Typography variant="body2" fontWeight="bold">{doc.metadata?.insured || 'N/A'}</Typography>
            </Grid>
            <Grid item xs={6}>
              <Typography variant="caption" sx={{ opacity: 0.7 }}>VEHICLE</Typography>
              <Typography variant="body2" fontWeight="bold" noWrap>{doc.metadata?.vehicle || 'N/A'}</Typography>
            </Grid>
          </Grid>
        </Box>

        <Box display="flex" justifyContent="space-between" alignItems="flex-end" mt={2}>
          <Box>
            <Typography variant="caption" sx={{ opacity: 0.7 }}>EFFECTIVE</Typography>
            <Typography variant="body2">{doc.metadata?.effective ? new Date(doc.metadata.effective).toLocaleDateString() : 'N/A'}</Typography>
          </Box>
          <Button 
            variant="contained" 
            size="small" 
            color="secondary" 
            startIcon={<DownloadIcon />}
            onClick={() => handleDownload(doc)}
            sx={{ borderRadius: 4, textTransform: 'none', boxShadow: 'none' }}
          >
            PDF
          </Button>
        </Box>
      </Box>
    </Paper>
  );

  return (
    <Box>
      <Typography variant="h4" fontWeight="bold" gutterBottom>
        My Documents
      </Typography>
      
      <Tabs 
        value={tabValue} 
        onChange={(e, v) => setTabValue(v)} 
        sx={{ mb: 3, borderBottom: 1, borderColor: 'divider' }}
      >
        <Tab label="ID Cards" icon={<IdIcon />} iconPosition="start" />
        <Tab label="Policy Contracts" icon={<DocIcon />} iconPosition="start" />
        <Tab label="Uploaded Files" icon={<UploadIcon />} iconPosition="start" />
      </Tabs>

      {loading ? (
        <Box display="flex" justifyContent="center" p={5}>
          <CircularProgress />
        </Box>
      ) : error ? (
        <Alert severity="error">{error}</Alert>
      ) : (
        <Box>
          {/* ID Cards Tab */}
          {tabValue === 0 && (
            <Grid container spacing={3}>
              {idCards.length > 0 ? idCards.map(doc => (
                <Grid item xs={12} md={6} lg={4} key={doc.id}>
                  <IdCardView doc={doc} />
                </Grid>
              )) : (
                <Grid item xs={12}>
                  <Alert severity="info">No ID Cards available. Do you have an active Auto policy?</Alert>
                </Grid>
              )}
            </Grid>
          )}

          {/* Contracts Tab */}
          {tabValue === 1 && (
            <Paper variant="outlined">
              <List>
                {contracts.map((doc, index) => (
                  <React.Fragment key={doc.id}>
                    <ListItem>
                      <ListItemIcon>
                        <PdfIcon color="error" />
                      </ListItemIcon>
                      <ListItemText 
                        primary={doc.title} 
                        secondary={`Policy: ${doc.policyNumber} • Date: ${new Date(doc.date).toLocaleDateString()}`} 
                      />
                      <ListItemSecondaryAction>
                        <IconButton edge="end" onClick={() => handleDownload(doc)}>
                          <DownloadIcon />
                        </IconButton>
                      </ListItemSecondaryAction>
                    </ListItem>
                    {index < contracts.length - 1 && <Divider />}
                  </React.Fragment>
                ))}
                {contracts.length === 0 && (
                  <Box p={3} textAlign="center">
                    <Typography color="text.secondary">No policy contracts found.</Typography>
                  </Box>
                )}
              </List>
            </Paper>
          )}

          {/* Uploads Tab */}
          {tabValue === 2 && (
            <Box>
              <input
                type="file"
                id="doc-upload-input"
                style={{ display: 'none' }}
                onChange={handleFileChange}
              />
              <Box mb={2} display="flex" justifyContent="flex-end">
                <Button 
                  variant="contained" 
                  startIcon={<UploadIcon />}
                  onClick={handleUploadClick}
                >
                  Upload New Document
                </Button>
              </Box>
              <Paper variant="outlined">
                <List>
                  {uploads.map((doc, index) => (
                    <React.Fragment key={doc.id}>
                      <ListItem>
                        <ListItemIcon>
                          <ImageIcon color="primary" />
                        </ListItemIcon>
                        <ListItemText 
                          primary={doc.title} 
                          secondary={`Uploaded on: ${new Date(doc.date).toLocaleDateString()}`} 
                        />
                        <ListItemSecondaryAction>
                          <IconButton edge="end" onClick={() => handleDownload(doc)}>
                            <DownloadIcon />
                          </IconButton>
                        </ListItemSecondaryAction>
                      </ListItem>
                      {index < uploads.length - 1 && <Divider />}
                    </React.Fragment>
                  ))}
                  {uploads.length === 0 && (
                    <Box p={3} textAlign="center">
                      <Typography color="text.secondary">No uploaded files yet.</Typography>
                    </Box>
                  )}
                </List>
              </Paper>
            </Box>
          )}
        </Box>
      )}
    </Box>
  );
};

export default Documents;
